name: Sync Data to Frontend Repo

on:
  schedule:
    - cron: '39 11 * * *' # Run every day at 11:39 (or later) UTC
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Checkout generator Repository
      uses: actions/checkout@v4
      with:
        repository: Haxe18/rebull-editions-generator
        fetch-depth: 1
        token: ${{ secrets.GENERATOR_PAT_TOKEN }}
        path: rebull-editions-generator
        sparse-checkout: |
          dist

    - name: Check for changes
      id: check_changes
      run: |
        if ! diff -q data/redbull_editions.json rebull-editions-generator/dist/redbull_editions.json; then
          echo "Changes detected in dist/ folder."
          echo "has_changes=true" >> $GITHUB_OUTPUT

          # Read in the changelog.md
          CHANGELOG_CONTENT=$(tail -n +3 rebull-editions-generator/dist/changelog.md)

          # Saves the current changelog.md content in envirmonment
          # Keep linebreakes with random delimiter
          delimiter=$(openssl rand -hex 8)
          echo "changelog_body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT

          cp rebull-editions-generator/dist/redbull_editions.json data/redbull_editions.json
        else
          echo "No changes detected."
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Get formatted date
      if: steps.check_changes.outputs.has_changes == 'true'
      id: get_date
      run: echo "TODAY_DATE=$(date +'%d/%m/%Y')" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        add-paths: |
          data/*
        branch: automated-update
        delete-branch: true
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        commit-message: "🔄 Update Red Bull Editions Data (${{ steps.get_date.outputs.TODAY_DATE }})"
        title: "🔄 Update Red Bull Editions Data (${{ steps.get_date.outputs.TODAY_DATE }})"
        body: |
          ## 🔄 Automated Data Update

          This PR contains updated Red Bull editions data from the generator repository.

          ### 📊 Changes Summary
          ${{ steps.check_changes.outputs.changelog_body }}

          ### 🚀 Next Steps
          1. Review the changes in `data/redbull_editions.json`
          2. Test the frontend locally if needed
          3. Approve and merge when ready

          ---

          _This PR was auto-generated by the data sync workflow._
        reviewers: |
          ${{ github.actor }}
        assignees: |
          ${{ github.actor }}
        labels: |
          data-update
          automated
        draft: false
